<a href="https://colab.research.google.com/github/jobissjo/Pytorch-Learning/blob/main/Learn/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.5.1+cu124'

# Introduction to Tensors

In [ ]:
# @title  Dimensions of tensor

# tensor is a scalar, vector,multi-dimensional matrix containing elements of a single data type

# bar simple, how many [] brackets in outer is how many dimensions

import torch
scalar = torch.tensor(7)
print("scalar:", scalar, 'dimension:', scalar.ndim)

vector = torch.tensor([1,2,3])
print("vector:", vector, 'dimension:', vector.ndim)

MATRIX = torch.tensor([[1,2,3],[4,5,6]])
print("MATRIX:", MATRIX, 'dimension:', MATRIX.ndim)

TENSOR = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("TENSOR:", TENSOR, 'dimension:', TENSOR.ndim)


scalar: tensor(7) dimension: 0
vector: tensor([1, 2, 3]) dimension: 1
MATRIX: tensor([[1, 2, 3],
        [4, 5, 6]]) dimension: 2
TENSOR: tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) dimension: 3


In [ ]:
# @title ### Shape and size of tensors

print("Scalar Shape:", scalar.shape, "| Scalar Size:", scalar.size())
print("Vector Shape:", vector.shape, "| Vector Size:", vector.size())
print("Matrix Shape:", MATRIX.shape, "| Matrix Size:", MATRIX.size())
print("Tensor Shape:", TENSOR.shape, "| Tensor Size:", TENSOR.size())

Scalar Shape: torch.Size([]) | Scalar Size: torch.Size([])
Vector Shape: torch.Size([3]) | Vector Size: torch.Size([3])
Matrix Shape: torch.Size([2, 3]) | Matrix Size: torch.Size([2, 3])
Tensor Shape: torch.Size([2, 2, 3]) | Tensor Size: torch.Size([2, 2, 3])


In [ ]:
# @title ### Random
# - we need to specify size in tuple, generate a number in given size [between 0-1 values]
random_number1 = torch.rand((2,3))
print('radom_number:', random_number1)

# range of
randon_int_number = torch.randint(0,100, size=(2,3))
print('randon_int_number:', randon_int_number)

radom_number: tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
randon_int_number: tensor([[67,  6, 49],
        [76, 73, 11]])


### why we need a random generating number?


*   Used to create random data for temporary testing
*   Adding randomness to datasets (e.g., shuffling data, we usually shuffle the data in training stage for better prediction).



In [ ]:
# @title ### Zeros and ones

# just generating zeros and one with alredy existing dim

zeros = torch.zeros(size=random_number1.shape) # generating same shape of zero
print('zeros:', zeros)

ones = torch.ones(size=random_number1.shape) # generating same shape of zero
print('ones:', ones)

zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# @title ### Arange and Alike

even_numbers = torch.arange(start=0, end=100, step=2)
print('even_numbers:', even_numbers) # same like python's 'range' function
print('even_numbers_count---:', even_numbers.size())

print('\n\n')
# Alike
zeros_like = torch.zeros_like(input=even_numbers)
print('zeros_like:', zeros_like)
print('zeros_like_count--:', even_numbers.size())

even_numbers: tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])
even_numbers_count---: torch.Size([50])



zeros_like: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
zeros_like_count--: torch.Size([50])


# Data Types -

[Documentation](https://pytorch.org/docs/stable/tensors.html)




## Getting information from tensors
1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [ ]:
rand_tensor = torch.rand(size=(4,5))
print(f"Data type: {rand_tensor.dtype}, Shape: {rand_tensor.shape} , Device: {rand_tensor.device}")

rand_int32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
print(f"Data type: {rand_int32_tensor.dtype}, Shape: {rand_int32_tensor.shape} , Device: {rand_int32_tensor.device}")

Data type: torch.float32, Shape: torch.Size([4, 5]) , Device: cpu
Data type: torch.int32, Shape: torch.Size([3]) , Device: cpu


## Manipulating Tensors


In [ ]:
# @title Normal operations

my_tensor = torch.tensor([1,2,3])

print("Before Operation Tensor:", my_tensor)

print("Addition               :", my_tensor + 10)
print("Subtraction            :", my_tensor - 10)
print("Multiplication         :", my_tensor * 10)
print("Division               :", my_tensor / 10)

Before Operation Tensor: tensor([1, 2, 3])
Addition               : tensor([11, 12, 13])
Subtraction            : tensor([-9, -8, -7])
Multiplication         : tensor([10, 20, 30])
Division               : tensor([0.1000, 0.2000, 0.3000])


In [ ]:
# @title Inbuilt Functions

print("Before Operation Tensor:", my_tensor)

print("Addition               :", torch.add(my_tensor, 10))
print("Subtraction            :", torch.sub(my_tensor, 10))
print("Multiplication         :", torch.mul(my_tensor, 10))
print("Division               :", torch.div(my_tensor, 10))

Before Operation Tensor: tensor([1, 2, 3])
Addition               : tensor([11, 12, 13])
Subtraction            : tensor([-9, -8, -7])
Multiplication         : tensor([10, 20, 30])
Division               : tensor([0.1000, 0.2000, 0.3000])


### Matrix Multiplication

In [ ]:
# @title Time taken with pytorch method
%%time

my_tensor1 = torch.tensor([[1,2,3],[4,5,6]])
my_tensor2 = torch.tensor([[7,8],[9,10],[11,12]])



torch.matmul(my_tensor1, my_tensor2)

CPU times: user 1.51 ms, sys: 95 µs, total: 1.6 ms
Wall time: 9.6 ms


tensor([[ 58,  64],
        [139, 154]])

In [ ]:
%%time


my_tensor1 @ my_tensor2

CPU times: user 641 µs, sys: 0 ns, total: 641 µs
Wall time: 557 µs


tensor([[ 58,  64],
        [139, 154]])

In [ ]:
# @title Time taken with normal python for loop
%%time

new_tensor = torch.zeros((2,2))
for i in range(len(my_tensor1)):
  for j in range(len(my_tensor2[0])):
    for k in range(len(my_tensor2)):
      new_tensor[i][j] += my_tensor1[i][k] * my_tensor2[k][j]

print(new_tensor)

tensor([[ 58.,  64.],
        [139., 154.]])
CPU times: user 905 µs, sys: 1.83 ms, total: 2.74 ms
Wall time: 2.69 ms


In [ ]:
import numpy as np


In [ ]:
# @title Time taken with numpy
%%time

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8],[9,10],[11,12]])

np.matmul(arr1, arr2)

CPU times: user 106 µs, sys: 17 µs, total: 123 µs
Wall time: 130 µs


array([[ 58,  64],
       [139, 154]])

In [ ]:
# @title Matrix multiplication with same array with transpose

my_tensor_new = torch.randint(1,10,size=(2,3))
print("New Tensor Shape:", my_tensor_new.shape)
print("New Tensor Transpose Shape:", my_tensor_new.T.shape)

# If we transpose, always diagonals are same always

my_tensor_new @ my_tensor_new.T

New Tensor Shape: torch.Size([2, 3])
New Tensor Transpose Shape: torch.Size([3, 2])


tensor([[77, 40],
        [40, 56]])

# Finding Max, Min, Mean, sum

In [ ]:
numbers = torch.arange(0, 101, 5)
numbers

print("Max:", torch.max(numbers), numbers.max())
print("MIN:", torch.min(numbers), numbers.min())

print("Sum:", torch.sum(numbers), numbers.sum())

print("Mean:", torch.mean(numbers.type(torch.float64)), numbers.type(torch.float64).mean())

Max: tensor(100) tensor(100)
MIN: tensor(0) tensor(0)
Sum: tensor(1050) tensor(1050)
Mean: tensor(50., dtype=torch.float64) tensor(50., dtype=torch.float64)


In [ ]:
# @title position of min, max

print("Max POSITION:", torch.argmax(numbers), numbers.argmax())
print("MIN POSITION:", torch.argmin(numbers), numbers.argmin())

Max POSITION: tensor(20) tensor(20)
MIN POSITION: tensor(0) tensor(0)


# Reshaping



*   Reshapping - reshape an input to defined shape

    *   if tensor have 8 elements, reshapping size need to equally splitabble (4*2) (2*4) like that

*   Stacking - combine multiple tensor h-stact(horizaontal), v-stack (vertical)
*   Sequeezing - remove all 1 dim from tensor
*   Unsequeezing - add 1 dim to a target tensor




In [ ]:
one_d_shape = torch.arange(1,11)
print(one_d_shape, 'Shape::', one_d_shape.shape)

reshaped_tensor = one_d_shape.reshape(5,2)
print(reshaped_tensor, 'Shape::', reshaped_tensor.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) Shape:: torch.Size([10])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]) Shape:: torch.Size([5, 2])


In [ ]:
# view will share the same memory address, change in anyone affect the both
copyied_d_shape = one_d_shape.view(5,2)
copyied_d_shape

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
copyied_d_shape[0][0] = 2423
copyied_d_shape, one_d_shape

(tensor([[2423,    2],
         [   3,    4],
         [   5,    6],
         [   7,    8],
         [   9,   10]]),
 tensor([2423,    2,    3,    4,    5,    6,    7,    8,    9,   10]))

In [ ]:
# squeeze
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
torch.squeeze(x)


torch.Size([2, 1, 2, 1, 2])


tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
new_not_squeeze = torch.tensor([[1,2,3]])
print(new_not_squeeze.shape)
new_squeeze = new_not_squeeze.squeeze()
print(new_squeeze.shape)

torch.Size([1, 3])
torch.Size([3])


In [ ]:
# @title Permute

# -- Returns a 'view' of the original tensor input with its dimensions permuted.

random_tensor = torch.rand(size=(2,3,4))
print("Tensor:", rand_tensor,"\nSize  :", random_tensor.shape)
print("\n\n")
permuted_tensor = random_tensor.permute(2,0,1)
print("PERMUTED Tensor:\n", permuted_tensor,"\nSize  :", permuted_tensor.shape)

Tensor: tensor([[0.5575, 0.1046, 0.7791, 0.0219, 0.7035],
        [0.6302, 0.9825, 0.0579, 0.9675, 0.5909],
        [0.8109, 0.1922, 0.2243, 0.2081, 0.4161],
        [0.2566, 0.5454, 0.9226, 0.4226, 0.9633]]) 
Size  : torch.Size([2, 3, 4])



PERMUTED Tensor:
 tensor([[[0.7519, 0.6129, 0.4666],
         [0.3114, 0.5682, 0.3663]],

        [[0.5310, 0.6665, 0.9324],
         [0.7208, 0.4495, 0.6332]],

        [[0.3236, 0.8458, 0.5726],
         [0.8007, 0.5603, 0.7023]],

        [[0.2983, 0.6264, 0.3594],
         [0.9221, 0.4626, 0.0626]]]) 
Size  : torch.Size([4, 2, 3])


## Indexing

In [ ]:
indexing_tensor = torch.arange(1,10).reshape(1,3,3)
indexing_tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
indexing_tensor[:,2:,2]

tensor([[9]])

## Numpy Array

In [ ]:
import torch

import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
torch_tensor = torch.tensor([1,2,3])
numpy_tensor = torch_tensor.numpy()
torch_tensor, numpy_tensor.dtype

(tensor([1, 2, 3]), dtype('int64'))

## Reproducability

In [ ]:
# Sets the seed for generating random numbers on all devices. Returns a torch.Generator object.
torch.manual_seed(42)
radom_tensors = torch.rand(size=(4,3))
radom_tensors

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [ ]:
!nvidia-smi

Sun Feb  2 11:12:54 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
tensor_mat = torch.tensor([[1,2,3],[4,5,6]], device=device)
tensor_mat

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')