<a href="https://colab.research.google.com/github/jobissjo/Pytorch-Learning/blob/main/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
radom_tensor = torch.rand(size=(7,7))
radom_tensor

tensor([[0.4326, 0.4010, 0.7565, 0.9055, 0.0690, 0.1624, 0.0277],
        [0.5024, 0.5534, 0.8971, 0.3279, 0.1869, 0.5538, 0.0144],
        [0.8956, 0.2462, 0.9581, 0.4128, 0.5174, 0.1935, 0.0108],
        [0.1105, 0.8048, 0.8639, 0.7235, 0.0943, 0.8163, 0.2399],
        [0.7347, 0.8039, 0.3389, 0.2409, 0.9753, 0.9352, 0.0879],
        [0.8751, 0.7277, 0.2918, 0.3796, 0.7219, 0.1607, 0.0892],
        [0.6504, 0.9169, 0.0814, 0.6531, 0.7846, 0.1111, 0.2695]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
radom_tensor2 = torch.rand(size=(1,7))
# Perform matrix multiplication
torch.matmul(radom_tensor, radom_tensor2.T)


tensor([[1.7691],
        [1.6237],
        [2.3120],
        [1.5744],
        [2.0646],
        [1.9700],
        [1.9222]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
radom_tensor = torch.rand(size=(7,7))
radom_tensor2 = torch.rand(size=(1,7)).T
# Matrix multiply tensors
torch.matmul(radom_tensor, radom_tensor2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [9]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU

# Create two random tensors on GPU
torch.cuda.manual_seed(1234)
radom_tensor = torch.rand(size=(2,3)).cuda()
torch.cuda.manual_seed(1234)
radom_tensor2 = torch.rand(size=(2,3)).cuda()
radom_tensor, radom_tensor2


(tensor([[0.8102, 0.9801, 0.1147],
         [0.3168, 0.6965, 0.9143]], device='cuda:0'),
 tensor([[0.9351, 0.9412, 0.5995],
         [0.0652, 0.5460, 0.1872]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
matmul = radom_tensor @ radom_tensor2.T
matmul

tensor([[1.7488, 0.6094],
        [1.4999, 0.5721]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
print(torch.max(matmul))
# Find min
torch.min(matmul)

tensor(1.7488, device='cuda:0')


tensor(0.5721, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max

print(torch.argmax(matmul))
# Find arg min
print(torch.argmin(matmul))

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed

torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand(size=(1,1,1,10))

# Remove single dimensions
sequeezed_tensor = torch.squeeze(rand_tensor)

# Print out tensors and their shapes
print("Tensor:", radom_tensor)
print("Shape:", radom_tensor.shape)
print("Squeezed Tensor:", sequeezed_tensor)
print("Shape:", sequeezed_tensor.shape)

Tensor: tensor([[0.8102, 0.9801, 0.1147],
        [0.3168, 0.6965, 0.9143]], device='cuda:0')
Shape: torch.Size([2, 3])
Squeezed Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape: torch.Size([10])
